### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by jurobystricky** [intel-secl/certificate-management-service#1]
This link gives me 404:
https://01.org/intel-secl/cms

**Comment by ddhawal** [comment]
There is a typo in the link, https://01.org/intel-secl has more details about the product. This particular component has been moved to https://github.com/intel-secl/intel-secl/tree/master/pkg/cms. We are in process of marking this repository (https://github.com/intel-secl/certificate-management-service) deprecated.
